# Generated by Django 6.0.5 on 2026-05-11 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='items.items')),
            ],
        ),
    ]
