# Generated by Django 6.0.5 on 2026-05-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Movements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')])),
                ('quantity', models.IntegerField()),
                ('cost_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='items.items')),
            ],
        ),
    ]
