# Generated by Django 6.0.5 on 2026-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_movements',
            name='cost_price',
            field=models.FloatField(null=True),
        ),
    ]
