# Generated by Django 6.0.5 on 2026-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_movements', '0002_alter_stock_movements_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_movements',
            name='sell_price',
            field=models.FloatField(null=True),
        ),
    ]
